name: build webrtc win

# 手动触发github actions
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2019
    
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        env:
          vs2019_install: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise'
        run: |
          call sync_for_win.bat
        shell: cmd

      - name: build
        env:
          vs2019_install: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise'
        run: |
          call build_for_win.bat
        shell: cmd